### PR TITLE
Adding icamerasrc-git-fix, removed ivsc-driver, fixed v4l2loopback typo

### PR DESCRIPTION
**Pull request by striczkof**
Fixes stefanpartheym/archlinux-ipu6-webcam#18 plus the dkms crying about same files when installing ivsc driver. Turns out, it's installed already through ipu6-dkms. Also renamed the v4l2loopback folder to reflect the package name and added a reminder to reboot (got me lol) because why not?

installing and uninstalling works smoothly on my Dell XPS 13 Plus 9320 running Arch Linux kernel 6.3.7-arch1-1, with KDE Plasma on Wayland. Gotta try in a truly fresh install within 3 days but should work flawless.

Working for Firefox, Discord, and OBS with workaround flag. Just crashes Kamoso when I select the virtual camera for some reason.

### CODE REVIEW

**Comment by sigboe** [comment]
LGTM :+1: 

I was planning on making a merge request for this this weekend, but I forgot about it, this also does more cleanup, and housework than what I had ready.

Great job! This restores this repo's main purpose, to be a user friendly way to get the camera working!

Only thing missing now is to go over and update the readme file, to reflect newer kernels!

**Comment by striczkof** [comment]
Thanks, I was legit crying for 5 hours trying to get my webcam work until I found your answer and tried removing ivsc-driver because it's conflicting with ipu6-dkms.

**Comment by stefanpartheym** [comment]
Guys, huge thanks for the contributions. It really makes things easy again.
I'll merge this one in a bit.

Best regards
Stefan

**Comment by stefanpartheym** [comment]
Hi @striczkof,
sorry I kinda merged your pull request too early I guess.
Turns out, installation fails due to:
(in German)
```
==> FEHLER: 70-ipu6-psys.rules wurde nicht im build Verzeichnis gefunden und ist keine URL.
```
(in English)
```
==> ERROR: 70-ipu6-psys.rules was not found in build directory and is not an URL.
```

After adding the file as `icamerasrc-git/70-ipu6-psys.rules`:
```
# This rule makes the Intel IPU6 sensor accessible to members of group 'video',
# allowing icamerasrc to be used as an unprivileged user.
SUBSYSTEM=="intel-ipu6-psys",GROUP="video",MODE="0660"
```

Installation works fine. 
Can you confirm? If yes, I'll just commit the file accordingly.

**Comment by elhossary** [comment]
Hi,
Let me hop in here.
I added ```icamerasrc-git/70-ipu6-psys.rules``` file manually, and it WORKS for the first time in my Alder lake X1 carbon

**Comment by striczkof** [comment]
Danke, hab ich vergessen xd

No bloody idea how I missed that file lol.
Installation might work fine but it may be needed so regular user applications can access the cam. We should add that one just to be safe. Submitted the PR https://github.com/stefanpartheym/archlinux-ipu6-webcam/pull/23#issue-1752577138

**Comment by stefanpartheym** [comment]
> Danke, hab ich vergessen xd
> 
> No bloody idea how I missed that file lol. Installation might work fine if removed from PKGBUILD but it may be needed so regular user applications can access the cam. We should add that one just to be safe. Submitted the PR #23

Haha, don't worry. Maybe the .gitignore was preventing the file to be shown in git status ;)

**Comment by petobens** [comment]
@elhossary I also have an X1 carbon with Arch and i tried with both 6.1.34-1-lts and 6.3.8 and cannot get the camera to work. Running `systemctl status v4l2-relayd.service` shows:
```
Jun 18 19:20:30 X1-Carbon systemd[1]: Starting v4l2-relay daemon service...
Jun 18 19:20:30 X1-Carbon systemd[1]: Started v4l2-relay daemon service.
Jun 18 19:20:30 X1-Carbon v4l2-relayd[45191]: gst_element_set_state: assertion 'GST_IS_ELEMENT (element)' failed
```
and `bash test.sh`:
```
(gst-launch-1.0:46779): GStreamer-CRITICAL **: 19:20:41.082: gst_element_link_pads_filtered: assertion 'GST_IS_BIN (parent)' failed
ERROR: pipeline could not be constructed: syntax error.
```
FWIW I'm using Xorg..  any ideas?

@stefanpartheym @striczkof any pointers are also greatly appreciated..

**Comment by Devidxyz** [comment]
I got an error on Dell XPS 13 Plus 9320 running Arch Linux kernel 6.5.3-arch1-1
```
configure: error:
      You need to install or upgrade the GStreamer development
      packages on your system. On debian-based systems these are
      libgstreamer1.0-dev; on RPM-based systems gstreamer1.0-devel.
      The minimum version required is 1.0.0.

==> ERROR: A failure occurred in build().
    Aborting...
ERROR: Failed to build/install: v4l2-relayd
```
The `gstreamer` package wasn't enough, I had to manually install `gst-libav` too (in case anyone gets the same error).

**Comment by JanusDC** [comment]
I confirm it works on the Lenovo ThinkPad X1 Yoga Gen8.
Thanks for this :-)

**Pull request merged**
