### PR TITLE
Fix for current lts kernel

### PR DESCRIPTION
**Pull request by struan-robertson**
Hi,

I managed to get everything working again on the current (6.6.58-1-lts) lts kernel. It seems like the camera drivers broke with kernel version 6.6.50 but whatever change broke them was fixed at some point between 51 and 55. However, v4l2-relayd stopped working for some reason, which is why people might  have been able to run `test.sh` but not use their cameras in their browsers. I have patched v4l2-relayd to work with the current version of v4l2loopback-dkms in the arch repos, so we don't need to use the older ubuntu patched version of v4l2loopback-dkms, which I think is what broke everything.

I have obviously only been able to test this on my laptop (Dell XPS 13 Plus 9320 with a ipu6ep sensor) but it should work for everyone.

Also, I tried updating all of the intel packages to the latest versions but this just broke everything, so I have pinned each package to a commit version. This should also ensure that new users of this repo aren't caught out by stuff like ipu6-camera-bins not building because intel changed the folder layout.

Thanks,
Struan

### CODE REVIEW

**Comment by stefanpartheym** [comment]
Hi @struan-robertson,

thanks for putting in the time and effort.

I tried your changes: Installation worked flawlessly. Test script `test.sh` also gives valid output. However, I still can't see any image when using a Browser (Chromium/Brave, Firefox).
So it seems to be an issue with my v4l2-relayd, as dmesg proves.

Related dmesg output:
```
...
[   14.690514] intel vsc not ready
[   14.806163] intel vsc not ready
[   14.835916] vsc_ace spi-INTC1094:00-5db76cf6-0a68-4ed6-9b78-0361635e2447: recv firmware id
[   15.012160] intel-ipu6-isys intel-ipu6-isys0: bind ov01a10 16-0036 nlanes is 1 port is 2
[   15.012457] intel-ipu6-isys intel-ipu6-isys0: All sensor registration completed.
...
[   93.277437] intel-ipu6-isys intel-ipu6-isys0: stream on ov01a10 16-0036
[  113.387622] intel-ipu6-isys intel-ipu6-isys0: stream off ov01a10 16-0036
[  126.014490] v4l2-relayd[899]: segfault at 0 ip 000070ba4524d6a0 sp 00007ffcc27ce720 error 4 in libc.so.6[70ba451d5000+171000] likely on CPU 14 (core 22, socket 0)
[  126.014523] Code: 66 2e 0f 1f 84 00 00 00 00 00 f3 0f 1e fa 48 81 7e 08 ff c9 9a 3b 77 42 55 48 89 e5 41 54 49 89 f4 53 48 89 fb e8 20 f3 ff ff <48> 8b 03 85 c0 74 19 48 8d 50 ff f0 48 0f b1 13 75 0e 5b 31 c0 41
[  126.954609] v4l2-relayd[4239]: segfault at 0 ip 00007da42e7446a0 sp 00007ffde24ee990 error 4 in libc.so.6[7da42e6cc000+171000] likely on CPU 0 (core 0, socket 0)
[  126.954626] Code: 66 2e 0f 1f 84 00 00 00 00 00 f3 0f 1e fa 48 81 7e 08 ff c9 9a 3b 77 42 55 48 89 e5 41 54 49 89 f4 53 48 89 fb e8 20 f3 ff ff <48> 8b 03 85 c0 74 19 48 8d 50 ff f0 48 0f b1 13 75 0e 5b 31 c0 41
[  127.889041] v4l2-relayd[4306]: segfault at 0 ip 000070bc537226a0 sp 00007ffed89800f0 error 4 in libc.so.6[70bc536aa000+171000] likely on CPU 1 (core 0, socket 0)
[  127.889055] Code: 66 2e 0f 1f 84 00 00 00 00 00 f3 0f 1e fa 48 81 7e 08 ff c9 9a 3b 77 42 55 48 89 e5 41 54 49 89 f4 53 48 89 fb e8 20 f3 ff ff <48> 8b 03 85 c0 74 19 48 8d 50 ff f0 48 0f b1 13 75 0e 5b 31 c0 41
[  141.916902] v4l2-relayd[4369]: segfault at 0 ip 00007438609846a0 sp 00007ffd548ffe80 error 4 in libc.so.6[74386090c000+171000] likely on CPU 1 (core 0, socket 0)
[  141.916925] Code: 66 2e 0f 1f 84 00 00 00 00 00 f3 0f 1e fa 48 81 7e 08 ff c9 9a 3b 77 42 55 48 89 e5 41 54 49 89 f4 53 48 89 fb e8 20 f3 ff ff <48> 8b 03 85 c0 74 19 48 8d 50 ff f0 48 0f b1 13 75 0e 5b 31 c0 41
[  142.936657] v4l2-relayd[4572]: segfault at 0 ip 00007c566b0006a0 sp 00007ffd2d6929b0 error 4 in libc.so.6[7c566af88000+171000] likely on CPU 1 (core 0, socket 0)
[  142.936685] Code: 66 2e 0f 1f 84 00 00 00 00 00 f3 0f 1e fa 48 81 7e 08 ff c9 9a 3b 77 42 55 48 89 e5 41 54 49 89 f4 53 48 89 fb e8 20 f3 ff ff <48> 8b 03 85 c0 74 19 48 8d 50 ff f0 48 0f b1 13 75 0e 5b 31 c0 41
[  143.928616] v4l2-relayd[4611]: segfault at 0 ip 00007ab8de0206a0 sp 00007ffe400eb590 error 4 in libc.so.6[7ab8ddfa8000+171000] likely on CPU 8 (core 16, socket 0)
[  143.928640] Code: 66 2e 0f 1f 84 00 00 00 00 00 f3 0f 1e fa 48 81 7e 08 ff c9 9a 3b 77 42 55 48 89 e5 41 54 49 89 f4 53 48 89 fb e8 20 f3 ff ff <48> 8b 03 85 c0 74 19 48 8d 50 ff f0 48 0f b1 13 75 0e 5b 31 c0 41
[  144.889753] v4l2-relayd[4649]: segfault at 0 ip 00007149fac716a0 sp 00007ffc3bb07960 error 4 in libc.so.6[7149fabf9000+171000] likely on CPU 1 (core 0, socket 0)
[  144.889779] Code: 66 2e 0f 1f 84 00 00 00 00 00 f3 0f 1e fa 48 81 7e 08 ff c9 9a 3b 77 42 55 48 89 e5 41 54 49 89 f4 53 48 89 fb e8 20 f3 ff ff <48> 8b 03 85 c0 74 19 48 8d 50 ff f0 48 0f b1 13 75 0e 5b 31 c0 41
[  145.657696] v4l2-relayd[4686]: segfault at 0 ip 00007f38f114d6a0 sp 00007ffd13f4c0c0 error 4 in libc.so.6[7f38f10d5000+171000] likely on CPU 7 (core 12, socket 0)
[  145.657729] Code: 66 2e 0f 1f 84 00 00 00 00 00 f3 0f 1e fa 48 81 7e 08 ff c9 9a 3b 77 42 55 48 89 e5 41 54 49 89 f4 53 48 89 fb e8 20 f3 ff ff <48> 8b 03 85 c0 74 19 48 8d 50 ff f0 48 0f b1 13 75 0e 5b 31 c0 41
[  146.614703] v4l2-relayd[4718]: segfault at 0 ip 000070001ca996a0 sp 00007ffefaca3a90 error 4 in libc.so.6[70001ca21000+171000] likely on CPU 4 (core 8, socket 0)
[  146.614727] Code: 66 2e 0f 1f 84 00 00 00 00 00 f3 0f 1e fa 48 81 7e 08 ff c9 9a 3b 77 42 55 48 89 e5 41 54 49 89 f4 53 48 89 fb e8 20 f3 ff ff <48> 8b 03 85 c0 74 19 48 8d 50 ff f0 48 0f b1 13 75 0e 5b 31 c0 41
```

I will try out some stuff and see if I can get it working.

**Comment by struan-robertson** [comment]
@stefanpartheym huh that is strange. I think `segfault at 0` means its trying to dereference a null pointer, but the only thing my patch did with v4l2-relayd was to redefine a macro so that it used the same signal as upstream v4l2loopback. 

Since `test.sh` runs, I think we can be fairly confident that all the intel side of things is running as expected. It might be worth uninstalling everything and trying again.`v4l2loopback-dkms-git-fix` has been replaced by `v4l2loopback-dkms` so check that the packages have correctly changed. Another potential issue is if there are already built `.tar.zst` files in a package directory, then makepkg will just use those rather than rebuilding the package, so make sure to delete them all.

As a temporary workaround, you could pipe the icamerasrc directly to v4l2loopback before a video call using `sudo gst-launch-1.0 icamerasrc ! video/x-raw,format=NV12,width=1280,height=720 ! videoconvert ! v4l2sink name=v4l2sink device=/dev/video0` (make sure the v4l2-relayd service is stopped), then kill the process once you are done.

If `v4l2-relayd` keeps crashing, you could try to get a core dump and I would be happy to take a look and maybe see where the issue is arising.

**Comment by stefanpartheym** [comment]
Hi @struan-robertson,

thanks a lot! The workaround via `sudo gst-launch-1.0 icamerasrc ! video/x-raw,format=NV12,width=1280,height=720 ! videoconvert ! v4l2sink name=v4l2sink device=/dev/video0` is sufficient for me for now. 

I merged the PR as it is definitely an improvement.
Will add note in the README for your suggested workaround.

**Comment by stefanpartheym** [comment]
Ok, fixed the issue with d1c471caf4099e25d392ad23a3410706692a8701. Everything works fine now.

**Pull request merged**
